spring:
  application:
    name: tracking-service

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

  liquibase:
    enabled: false

tracking:
  rate-limit: 25

logging:
  level:
    org.springframework.data.redis: DEBUG
