spring:
  application:
    name: tracking-service

  profiles:
    active: default

  redis:
    url: redis://default:gYKxxMVbJRSSYRdAaeuPVcDswvWJdxQW@switchback.proxy.rlwy.net:22122

  liquibase:
    enabled: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

tracking:
  rate-limit: 25

logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
    org.springframework.boot.autoconfigure.data.redis: DEBUG