spring:
  application:
    name: tracking-service

  redis:
    host: ${REDISHOST}
    port: ${REDISPORT}
    password: ${REDISPASSWORD}

  liquibase:
    enabled: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

tracking:
  rate-limit: 25

logging:
  level:
    org.springframework.data.redis: DEBUG